RECUR_DAILY = 'DAILY'
RECUR_WEEKLY = 'WEEKLY'
RECUR_BIWEEKLY = 'BI_WEEKLY'
RECUR_MONTHLY = 'MONTHLY'
RECUR_YEARLY = 'YEARLY'

RECUR_OPTIONS = [
  (RECUR_DAILY, 'Daily'),
  (RECUR_WEEKLY, 'Weekly'),
  (RECUR_BIWEEKLY, 'Bi Weekly'),
  (RECUR_MONTHLY, 'Monthly'),
  (RECUR_YEARLY, 'Yearly')
]
