# Generated by Django 5.1.5 on 2025-01-22 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_expense'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='user',
            new_name='created_by',
        ),
    ]
