# Generated by Django 5.1.5 on 2025-01-22 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0003_rename_user_expense_created_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='category',
            new_name='category_name',
        ),
    ]
