# Generated by Django 5.1.5 on 2025-01-22 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0004_rename_category_expense_category_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='category_name',
            new_name='category_id',
        ),
    ]
